apiVersion: apps/v1 
kind: Deployment
metadata:
  name: consumer 
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          env:
            - name: RABBITMQ_HOST 
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-credentials 
                  key: password 
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
