apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: kube-proj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: rabbitmq
  namespace: kube-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template: 
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq 
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username 
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials 
                  key: password
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

--- 

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: kube-proj
spec:
  type: ClusterIP 
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: management
      protocol: TCP
      port: 15672

