apiVersion: apps/v1 
kind: Deployment
metadata:
  name: consumer 
  namespace: kube-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: fabioteichmann/kube-proj-consumer:latest
          env:
            - name: RABBITMQ_HOST 
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom: 
                secretKeyRef:
                  name: rabbitmq-credentials 
                  key: password 
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
