apiVersion: apps/v1 
kind: Deployment
metadata:
  name: producer
  namespace: {{ .Values.global.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.global.rabbitmq.hostName }}
            - name: RABBITMQ_PORT 
              value: "{{ .Values.global.rabbitmq.port }}"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
