apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: {{ include "kube-proj.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"

---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.application.rabbitmq.svcName }}
  namespace:  {{ include "kube-proj.name" . }}
spec:
  replicas: {{ .Values.application.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.rabbitmq.svcName }}
  template: 
    metadata:
      labels:
        app: {{ .Values.application.rabbitmq.svcName }}
    spec:
      containers:
        - name: {{ .Values.application.rabbitmq.svcName }} 
          image: rabbitmq:3-management
          ports:
            - containerPort: {{ .Values.application.rabbitmq.ampqPort }}
            - containerPort: {{ .Values.application.rabbitmq.mgtPort }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          {{- with .Values.application.env }}
          env:
            {{- toYaml .Values.application.env | nindent 12}}
          {{- end}}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

--- 

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.rabbitmq.svcName }}
  namespace: {{ include "kube-proj.name" . }}
  labels: 
    {{- include "kube-project.labels" . | nindent 4 }}
spec:
  type: ClusterIP 
  selector:
    app: {{ .Values.application.rabbitmq.svcName }}
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.application.rabbitmq.amqpPort }}
    - name: management
      protocol: TCP
      port: {{ .Values.application.rabbitmq.mgtPort }}

